バッチ処理を施した場合

In [1]:
import numpy as np
import random  

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:
def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network

In [4]:
def forward(network, x):
    # layer 1
    W1=network['W1']
    b1=network['b1']
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    # layer2
    W2=network['W2']
    b2=network['b2']
    a2=np.dot(z1,W2)+b2
    z2=sigmoid(a2)
    #layer3
    W3=network['W3']
    b3=network['b3']
    a3=np.dot(z2,W3)+b3
    y=a3#恒等写像
    return y

In [5]:
network = init_network()
batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)
    print(y_batch)
    print("-"*len(str(y_batch[1])))

[[ 0.31813215  0.69917869]
 [ 0.31300037  0.68776365]
 [ 0.31209982  0.68577431]
 [ 0.3158885   0.69418615]
 [ 0.31346103  0.68878358]
 [ 0.31528723  0.69284141]
 [ 0.31313863  0.68806963]
 [ 0.31216723  0.68593064]
 [ 0.31511248  0.69246794]
 [ 0.31677685  0.69615361]
 [ 0.31140681  0.68424347]
 [ 0.3169679   0.69659049]
 [ 0.31431938  0.6906971 ]
 [ 0.31507388  0.69237834]
 [ 0.31500057  0.6922054 ]
 [ 0.31110539  0.68356872]]
-------------------------
[[ 0.31323348  0.68829246]
 [ 0.31422793  0.69049696]
 [ 0.31639142  0.69530892]
 [ 0.31312189  0.68803761]
 [ 0.31378166  0.68951724]
 [ 0.31398621  0.68997119]
 [ 0.31612154  0.69470151]
 [ 0.31285741  0.68745625]
 [ 0.31246606  0.68659012]
 [ 0.3117773   0.68505027]
 [ 0.31239276  0.68642747]
 [ 0.31494501  0.69208694]
 [ 0.31591385  0.6942403 ]
 [ 0.31124907  0.68388592]
 [ 0.31005311  0.68123163]
 [ 0.30990367  0.68089997]]
-------------------------
[[ 0.3117729   0.68504068]
 [ 0.31786266  0.6985791 ]
 [ 0.31138223  0.6841825 ]
 